"use strict";

// Updating the left-hand colours ---------------------------------------------

function colourUpdateLeft(colourClass){
  let scrollColour = document.querySelector(`.${colourClass}`);
  scrollColour.addEventListener( "click", colourBG );

  let leftContainer = document.querySelector(".colourBG_1");
  let textUpdate = document.querySelector(".colourText_1");

  function colourBG(){

    let style = window.getComputedStyle(scrollColour);
    let colour = style.getPropertyValue("background-color");
    leftContainer.style.background = colour;

    let description = scrollColour.textContent;
    textUpdate.textContent = "The colour displayed is: " + description;
    textUpdate.style.fontFamily = "futura";
    textUpdate.style.fontSize = "1em";
  }
}
colourUpdateLeft("white");
colourUpdateLeft("snow");
colourUpdateLeft("honeydew");
colourUpdateLeft("mintcream");
colourUpdateLeft("azure");
colourUpdateLeft("aliceblue");
colourUpdateLeft("ghostwhite");
colourUpdateLeft("whitesmoke");
colourUpdateLeft("seashell");
colourUpdateLeft("beige");
colourUpdateLeft("oldlace");
colourUpdateLeft("floralwhite");
colourUpdateLeft("ivory");
colourUpdateLeft("antiquewhite");
colourUpdateLeft("linen");
colourUpdateLeft("lavenderblush");
colourUpdateLeft("mistyrose");
colourUpdateLeft("cornsilk");
colourUpdateLeft("blanchedalmond");
colourUpdateLeft("bisque");
colourUpdateLeft("navajowhite");
colourUpdateLeft("wheat");
colourUpdateLeft("burlywood");
colourUpdateLeft("tan");
colourUpdateLeft("rosybrown");
colourUpdateLeft("sandybrown");
colourUpdateLeft("goldenrod");
colourUpdateLeft("darkgoldenrod");
colourUpdateLeft("peru");
colourUpdateLeft("chocolate");
colourUpdateLeft("saddlebrown");
colourUpdateLeft("sienna");
colourUpdateLeft("brown");
colourUpdateLeft("maroon");
colourUpdateLeft("lightsalmon");
colourUpdateLeft("salmon");
colourUpdateLeft("darksalmon");
colourUpdateLeft("lightcoral");
colourUpdateLeft("indianred");
colourUpdateLeft("crimson");
colourUpdateLeft("firebrick");
colourUpdateLeft("darkred");
colourUpdateLeft("red");
colourUpdateLeft("orangered");
colourUpdateLeft("tomato");
colourUpdateLeft("coral");
colourUpdateLeft("darkorange");
colourUpdateLeft("orange");
colourUpdateLeft("yellow");
colourUpdateLeft("lightyellow");
colourUpdateLeft("lemonchiffon");
colourUpdateLeft("lightgoldenrodyellow");
colourUpdateLeft("papayawhip");
colourUpdateLeft("moccasin");
colourUpdateLeft("peachpuff");
colourUpdateLeft("palegoldenrod");
colourUpdateLeft("khaki");
colourUpdateLeft("darkkhaki");
colourUpdateLeft("gold");
colourUpdateLeft("darkolivegreen");
colourUpdateLeft("olive");
colourUpdateLeft("olivedrab");
colourUpdateLeft("yellowgreen");
colourUpdateLeft("limegreen");
colourUpdateLeft("lime");
colourUpdateLeft("lawngreen");
colourUpdateLeft("chartreuse");
colourUpdateLeft("greenyellow");
colourUpdateLeft("springgreen");
colourUpdateLeft("mediumspringgreen");
colourUpdateLeft("lightgreen");
colourUpdateLeft("palegreen");
colourUpdateLeft("darkseagreen");
colourUpdateLeft("mediumaquamarine");
colourUpdateLeft("mediumseagreen");
colourUpdateLeft("seagreen");
colourUpdateLeft("forestgreen");
colourUpdateLeft("green");
colourUpdateLeft("darkgreen");
colourUpdateLeft("aqua");
colourUpdateLeft("cyan");
colourUpdateLeft("lightcyan");
colourUpdateLeft("paleturquoise");
colourUpdateLeft("aquamarine");
colourUpdateLeft("turquoise");
colourUpdateLeft("mediumturquoise");
colourUpdateLeft("darkturquoise");
colourUpdateLeft("lightseagreen");
colourUpdateLeft("cadetblue");
colourUpdateLeft("darkcyan");
colourUpdateLeft("teal");
colourUpdateLeft("lightsteelblue");
colourUpdateLeft("powderblue");
colourUpdateLeft("lightblue");
colourUpdateLeft("skyblue");
colourUpdateLeft("lightskyblue");
colourUpdateLeft("deepskyblue");
colourUpdateLeft("dodgerblue");
colourUpdateLeft("cornflowerblue");
colourUpdateLeft("steelblue");
colourUpdateLeft("royalblue");
colourUpdateLeft("blue");
colourUpdateLeft("mediumblue");
colourUpdateLeft("darkblue");
colourUpdateLeft("navy");
colourUpdateLeft("midnightblue");
colourUpdateLeft("pink");
colourUpdateLeft("lightpink");
colourUpdateLeft("hotpink");
colourUpdateLeft("deeppink");
colourUpdateLeft("palevioletred");
colourUpdateLeft("mediumvioletred");
colourUpdateLeft("lavender");
colourUpdateLeft("thistle");
colourUpdateLeft("plum");
colourUpdateLeft("violet");
colourUpdateLeft("orchid");
colourUpdateLeft("fuchsia");
colourUpdateLeft("magenta");
colourUpdateLeft("mediumorchid");
colourUpdateLeft("mediumpurple");
colourUpdateLeft("blueviolet");
colourUpdateLeft("darkviolet");
colourUpdateLeft("darkorchid");
colourUpdateLeft("darkmagenta");
colourUpdateLeft("purple");
colourUpdateLeft("indigo");
colourUpdateLeft("darkslateblue");
colourUpdateLeft("slateblue");
colourUpdateLeft("mediumslateblue");
colourUpdateLeft("gainsboro");
colourUpdateLeft("lightgray");
colourUpdateLeft("silver");
colourUpdateLeft("darkgray");
colourUpdateLeft("gray");
colourUpdateLeft("dimgray");
colourUpdateLeft("lightslategray");
colourUpdateLeft("slategray");
colourUpdateLeft("darkslategray");
colourUpdateLeft("black");

// Updating the right-hand colours ---------------------------------------------

function colourUpdateRight(colourClass){
  let scrollColour = document.querySelector(`.${colourClass}`);
  scrollColour.addEventListener( "click", colourBG );

  let leftContainer = document.querySelector(".colourBG_2");
  let textUpdate = document.querySelector(".colourText_2");

  function colourBG(){

    let style = window.getComputedStyle(scrollColour);
    let colour = style.getPropertyValue("background-color");
    leftContainer.style.background = colour;

    let description = scrollColour.textContent;
    textUpdate.textContent = "The colour displayed is: " + description;
    textUpdate.style.fontFamily = "futura";
    textUpdate.style.fontSize = "1em";
  }
}
colourUpdateRight("white_2");
colourUpdateRight("snow_2");
colourUpdateRight("honeydew_2");
colourUpdateRight("mintcream_2");
colourUpdateRight("azure_2");
colourUpdateRight("aliceblue_2");
colourUpdateRight("ghostwhite_2");
colourUpdateRight("whitesmoke_2");
colourUpdateRight("seashell_2");
colourUpdateRight("beige_2");
colourUpdateRight("oldlace_2");
colourUpdateRight("floralwhite_2");
colourUpdateRight("ivory_2");
colourUpdateRight("antiquewhite_2");
colourUpdateRight("linen_2");
colourUpdateRight("lavenderblush_2");
colourUpdateRight("mistyrose_2");
colourUpdateRight("cornsilk_2");
colourUpdateRight("blanchedalmond_2");
colourUpdateRight("bisque_2");
colourUpdateRight("navajowhite_2");
colourUpdateRight("wheat_2");
colourUpdateRight("burlywood_2");
colourUpdateRight("tan_2");
colourUpdateRight("rosybrown_2");
colourUpdateRight("sandybrown_2");
colourUpdateRight("goldenrod_2");
colourUpdateRight("darkgoldenrod_2");
colourUpdateRight("peru_2");
colourUpdateRight("chocolate_2");
colourUpdateRight("saddlebrown_2");
colourUpdateRight("sienna_2");
colourUpdateRight("brown_2");
colourUpdateRight("maroon_2");
colourUpdateRight("lightsalmon_2");
colourUpdateRight("salmon_2");
colourUpdateRight("darksalmon_2");
colourUpdateRight("lightcoral_2");
colourUpdateRight("indianred_2");
colourUpdateRight("crimson_2");
colourUpdateRight("firebrick_2");
colourUpdateRight("darkred_2");
colourUpdateRight("red_2");
colourUpdateRight("orangered_2");
colourUpdateRight("tomato_2");
colourUpdateRight("coral_2");
colourUpdateRight("darkorange_2");
colourUpdateRight("orange_2");
colourUpdateRight("yellow_2");
colourUpdateRight("lightyellow_2");
colourUpdateRight("lemonchiffon_2");
colourUpdateRight("lightgoldenrodyellow_2");
colourUpdateRight("papayawhip_2");
colourUpdateRight("moccasin_2");
colourUpdateRight("peachpuff_2");
colourUpdateRight("palegoldenrod_2");
colourUpdateRight("khaki_2");
colourUpdateRight("darkkhaki_2");
colourUpdateRight("gold_2");
colourUpdateRight("darkolivegreen_2");
colourUpdateRight("olive_2");
colourUpdateRight("olivedrab_2");
colourUpdateRight("yellowgreen_2");
colourUpdateRight("limegreen_2");
colourUpdateRight("lime_2");
colourUpdateRight("lawngreen_2");
colourUpdateRight("chartreuse_2");
colourUpdateRight("greenyellow_2");
colourUpdateRight("springgreen_2");
colourUpdateRight("mediumspringgreen_2");
colourUpdateRight("lightgreen_2");
colourUpdateRight("palegreen_2");
colourUpdateRight("darkseagreen_2");
colourUpdateRight("mediumaquamarine_2");
colourUpdateRight("mediumseagreen_2");
colourUpdateRight("seagreen_2");
colourUpdateRight("forestgreen_2");
colourUpdateRight("green_2");
colourUpdateRight("darkgreen_2");
colourUpdateRight("aqua_2");
colourUpdateRight("cyan_2");
colourUpdateRight("lightcyan_2");
colourUpdateRight("paleturquoise_2");
colourUpdateRight("aquamarine_2");
colourUpdateRight("turquoise_2");
colourUpdateRight("mediumturquoise_2");
colourUpdateRight("darkturquoise_2");
colourUpdateRight("lightseagreen_2");
colourUpdateRight("cadetblue_2");
colourUpdateRight("darkcyan_2");
colourUpdateRight("teal_2");
colourUpdateRight("lightsteelblue_2");
colourUpdateRight("powderblue_2");
colourUpdateRight("lightblue_2");
colourUpdateRight("skyblue_2");
colourUpdateRight("lightskyblue_2");
colourUpdateRight("deepskyblue_2");
colourUpdateRight("dodgerblue_2");
colourUpdateRight("cornflowerblue_2");
colourUpdateRight("steelblue_2");
colourUpdateRight("royalblue_2");
colourUpdateRight("blue_2");
colourUpdateRight("mediumblue_2");
colourUpdateRight("darkblue_2");
colourUpdateRight("navy_2");
colourUpdateRight("midnightblue_2");
colourUpdateRight("pink_2");
colourUpdateRight("lightpink_2");
colourUpdateRight("hotpink_2");
colourUpdateRight("deeppink_2");
colourUpdateRight("palevioletred_2");
colourUpdateRight("mediumvioletred_2");
colourUpdateRight("lavender_2");
colourUpdateRight("thistle_2");
colourUpdateRight("plum_2");
colourUpdateRight("violet_2");
colourUpdateRight("orchid_2");
colourUpdateRight("fuchsia_2");
colourUpdateRight("magenta_2");
colourUpdateRight("mediumorchid_2");
colourUpdateRight("mediumpurple_2");
colourUpdateRight("blueviolet_2");
colourUpdateRight("darkviolet_2");
colourUpdateRight("darkorchid_2");
colourUpdateRight("darkmagenta_2");
colourUpdateRight("purple_2");
colourUpdateRight("indigo_2");
colourUpdateRight("darkslateblue_2");
colourUpdateRight("slateblue_2");
colourUpdateRight("mediumslateblue_2");
colourUpdateRight("gainsboro_2");
colourUpdateRight("lightgray_2");
colourUpdateRight("silver_2");
colourUpdateRight("darkgray_2");
colourUpdateRight("gray_2");
colourUpdateRight("dimgray_2");
colourUpdateRight("lightslategray_2");
colourUpdateRight("slategray_2");
colourUpdateRight("darkslategray_2");
colourUpdateRight("black_2");

// Reset Function --------------------------------------------------------------

document.querySelector("#reset_btn_1").addEventListener("click", reset_btn_left);
document.querySelector("#reset_btn_2").addEventListener("click", reset_btn_right);

function reset_btn_left(){
  let leftContainer = document.querySelector(".colourBG_1");
  let textUpdate = document.querySelector(".colourText_1");
  let scroll_1 = document.querySelector(".colourScroll_1");

    leftContainer.style.background = "white";
    textUpdate.textContent = "The colour displayed is: White";
    textUpdate.style.fontFamily = "futura";
    textUpdate.style.fontSize = "1em";
    scroll_1.scrollTop = 0;
}

function reset_btn_right(){
  let leftContainer = document.querySelector(".colourBG_2");
  let textUpdate = document.querySelector(".colourText_2");
  let scroll_2 = document.querySelector(".colourScroll_2");

    leftContainer.style.background = "white";
    textUpdate.textContent = "The colour displayed is: White";
    textUpdate.style.fontFamily = "futura";
    textUpdate.style.fontSize = "1em";
    scroll_2.scrollTop = 0;
}
